sudo: false
language: node_js
node_js:
  - "4"
  - "5"
  - "6"
  - "7"
os:
  - linux
cache:
  directories:
    - node_modules
before_install:
  - "test ! -d node_modules || npm prune"
  - "test ! -d node_modules || npm rebuild"
script: "npm run-script test-cov"
after_script: "npm i coveralls@~2.11 && cat ./coverage/lcov.info | coveralls"
env:
 - CC=clang CXX=clang++ npm_config_clang=1
services:
  - mongodb
notifications:
  email:
    on_success: never
